-- AlterTable
ALTER TABLE "grades" ALTER COLUMN "oral_test" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "small_test" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "big_test" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "midterm_exam" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "final_exam" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "subject_average" SET DATA TYPE DOUBLE PRECISION;
